import React, { useEffect, useState } from 'react';
import { Artwork } from './Artwork';

const directions = [
  { name: 'Living Systems', short: 'Sculptural / responsive / precise', premise: 'The portfolio is a living system.', description: 'One responsive object becomes the connective tissue between the introduction, work, and process. Each project changes its structure and material. The visitor moves through one continuous story.', ai: 'An optional “Find a starting point” tool maps a visitor’s brief to a small set of relevant case studies, with evidence for each match. It does one useful job and then gets out of the way.', technique: 'Production direction: a custom WebGL material, pointer-driven deformation, and scroll-linked transitions. ThreeUI’s Liquid Form and Structure Flow are useful studies. This preview uses original Canvas geometry.', tradeoff: 'Strongest overall direction. Memorable at first glance, while keeping the work easy to find. Requires restraint: the sculpture must eventually hand the stage to project imagery.' },
  { name: 'Field Notes', short: 'Editorial / tactile / curious', premise: 'A working collection of ideas.', description: 'An oversized editorial index opens into annotated studies. Sketches, prototypes, and decisions live together. A visitor can manipulate an idea before reading the story behind it.', ai: 'Inside selected case studies, an optional “Change a constraint” experiment would generate a bounded alternative and explain its tradeoffs using the documented project context.', technique: 'Production direction: tactile page transitions, depth on project images, and small interactive material studies. ThreeUI’s Sketchbook and Woven Cloth are references for focused experiments.', tradeoff: 'Best for communicating taste and judgment. Easier to maintain and lighter on devices. The interactive studies need to demonstrate a real design decision, not simply decorate the page.' },
  { name: 'Orbit', short: 'Spatial / connected / exploratory', premise: 'Follow the connections.', description: 'A navigable atlas connects work, experiments, and ideas. Select an object to reveal its story in place. The world is the index, with a conventional list available at every moment.', ai: 'AI would suggest meaningful connections between projects from their source material. Visitors can inspect “Why connected?” and follow the cited evidence. No persona or conversation required.', technique: 'Production direction: a small Three.js scene, camera easing, object selection, and semantic HTML controls. ThreeUI’s Orbital Sphere and Constellation Field offer relevant visual studies.', tradeoff: 'Most exploratory; closest to the ambition of the existing game. More complex to make accessible and responsive. The atlas needs enough varied work to justify the spatial navigation.' },
];
const chapters = [
  { label: 'Intelligent interfaces', title: 'A more useful kind of intelligence.', category: '01 / Intelligence', text: 'How can an interface make a powerful system feel approachable? The AI-enabled webOS is a starting point for exploring how intelligence becomes a useful part of everyday tools.', link: 'https://os.dzierson.com/', cta: 'Explore webOS', note: 'AI-enabled webOS', angle: 'Making complex capabilities understandable', question: 'The interface is the product. What should the system do on its own, and where should the person stay in control?' },
  { label: 'Digital experiences', title: 'A place worth getting lost in.', category: '02 / Experience', text: 'World exploration started with a simple invitation: step inside and discover. This direction turns that curiosity into a portfolio where every interaction leads to the work.', link: 'https://dzierson.com/', cta: 'Visit the current portfolio', note: 'World exploration', angle: 'Turning exploration into discovery', question: 'What is the smallest interaction that makes someone want to keep exploring? Remove friction before adding another mechanic.' },
  { label: 'Design & technology', title: 'Ideas become real by making.', category: '03 / Practice', text: '“I love to design, and I also love to build.” A portfolio can make that relationship visible through the choices, experiments, and prototypes behind the finished work.', link: 'https://github.com/wdzierson/shimmer-project-showcase-pub', cta: 'View portfolio source', note: 'An open-source portfolio', angle: 'Closing the distance between idea and implementation', question: 'What did building the prototype reveal that a static design could not? Show the decision, then show the thing it changed.' },
];
const initial = () => { const value = Number(new URLSearchParams(location.search).get('direction')); return value >= 1 && value <= 3 ? value - 1 : 0; };
export default function App() {
  const [mode, setMode] = useState(initial);
  const [chapter, setChapter] = useState(0);
  const [energy, setEnergy] = useState(35);
  const [paused, setPaused] = useState(false);
  const [notes, setNotes] = useState(false);
  const [lens, setLens] = useState('Overview');
  const [list, setList] = useState(false);
  const direction = directions[mode]; const selected = chapters[chapter];
  useEffect(() => { document.title = `${direction.name} — Will Dzierson`; }, [direction]);
  useEffect(() => { const update = () => setMode(initial()); window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update); }, []);
  function changeMode(index: number) { setMode(index); setChapter(0); setLens('Overview'); setList(false); const url = new URL(location.href); url.searchParams.set('direction', String(index + 1)); history.pushState({}, '', url); window.scrollTo({ top: 0, behavior: 'instant' }); }
  return <div className={`portfolio mode-${mode}`}>
    <a className="skip-link" href="#work">Skip to work</a>
    <div className="concept-bar"><a className="concept-label" href="/os.html">Try 04 / Aspect desktop ↗</a><div className="concept-tabs" aria-label="Portfolio direction">{directions.map((d, i) => <button key={d.name} aria-pressed={mode === i} onClick={() => changeMode(i)}><span>0{i + 1}</span> {d.name}</button>)}</div><button className="notes-toggle" aria-expanded={notes} aria-controls="direction-notes" onClick={() => setNotes(!notes)}>{notes ? 'Close notes −' : 'Concept notes +'}</button></div>
    {notes && <aside className="direction-notes" id="direction-notes"><div><span className="eyebrow">Direction 0{mode + 1} / {direction.short}</span><h2>{direction.premise}</h2><p>{direction.description}</p></div><div><h3>Where AI earns its place</h3><p>{direction.ai}</p><h3>Making it real</h3><p>{direction.technique}</p><p><strong>{direction.tradeoff}</strong></p><small>Interaction prototype. Content is adapted from the current local portfolio and your brief; project narratives are proposed, not completed case studies. AI features described here are not connected.</small></div></aside>}
    <header className="site-header"><a className="wordmark" href="/concepts.html">Will Dzierson<span className="wordmark-dot">●</span></a><span className="identity">Design technologist<br/>&amp; AI entrepreneur</span><nav aria-label="Main"><a href="#work">{mode === 2 ? 'The atlas' : mode === 1 ? 'The collection' : 'Selected work'}</a><a href="mailto:will+hello@dzierson.com">Let’s talk <span>↗</span></a></nav></header>
    <main>
      {mode === 0 && <section className="hero systems"><div className="hero-kicker eyebrow"><span className="status-dot"/>Independent thinking. Connected practice.</div><div className="sculpture"><Artwork mode={mode} chapter={chapter} energy={energy} paused={paused}/></div><h1>I make<br/>complex things<br/><em>feel human.</em></h1><div className="hero-aside"><span className="tiny-cross">+</span><p>At the intersection of<br/>design, technology,<br/>and what comes next.</p><a className="round-link" href="#work" aria-label="Explore selected work">↙</a></div><div className="hero-bottom"><span>Design is how it feels.<br/>Building is how I find out.</span><div className="art-controls"><label htmlFor="energy">Structure</label><input id="energy" type="range" min="0" max="100" value={energy} onChange={e => setEnergy(Number(e.target.value))}/><button onClick={() => setPaused(!paused)} aria-pressed={paused}>{paused ? 'Resume motion' : 'Pause motion'}</button></div><span className="move-hint">Move across the form to influence it ↗</span></div></section>}
      {mode === 1 && <section className="hero field"><div className="field-heading"><span className="eyebrow">A collection by Will Dzierson</span><h1>Thoughtfully<br/>made.<br/><em>Never finished.</em></h1><p>Notes from the space between<br/>having an idea and making it real.</p><a className="text-link" href="#work">Open the collection <span>↘</span></a></div><div className="field-plate"><div className="plate-meta"><span>Study 00{chapter + 1}</span><span>Form &amp; possibility</span></div><Artwork mode={mode} chapter={chapter} energy={energy} paused={paused}/><div className="plate-caption"><span>A landscape of possibilities.</span><label htmlFor="contour">Contour <input id="contour" type="range" min="0" max="100" value={energy} onChange={e => setEnergy(Number(e.target.value))}/></label></div><button className="plate-pause" onClick={() => setPaused(!paused)} aria-pressed={paused}>{paused ? 'Resume study' : 'Pause study'}</button></div><span className="field-margin">OBSERVE → QUESTION → MAKE → REPEAT</span></section>}
      {mode === 2 && <section className="hero orbit"><div className="orbit-heading"><span className="eyebrow">An atlas of work &amp; ideas</span><h1>Everything<br/>is <em>connected.</em></h1><p>Design. Intelligence. A little curiosity.<br/>Pick a point and follow the thread.</p></div><div className="orbit-system"><div className="orbit-ring ring-a"/><div className="orbit-ring ring-b"/><Artwork mode={mode} chapter={chapter} energy={energy} paused={paused}/>{chapters.map((c, i) => <button key={c.label} className={`orbit-node node-${i} ${chapter === i ? 'selected' : ''}`} aria-pressed={chapter === i} onClick={() => { setChapter(i); setLens('Overview'); }}><span className="node-mark">0{i + 1}</span><span>{c.label}<small>{i === 0 ? 'Systems that assist' : i === 1 ? 'Places to explore' : 'Ideas made tangible'}</small></span></button>)}</div><div className="orbit-bottom"><button className="text-link" onClick={() => setList(!list)} aria-expanded={list}>{list ? 'Close index −' : 'Open index +'}</button><p aria-live="polite"><span>Selected / 0{chapter + 1}</span>{selected.note} <a href="#work" aria-label={`Read about ${selected.note}`}>↘</a></p><button onClick={() => setPaused(!paused)} aria-pressed={paused}>{paused ? 'Resume motion' : 'Pause motion'}</button></div>{list && <div className="orbit-index">{chapters.map((c, i) => <a href="#work" key={c.label} onClick={() => setChapter(i)}>0{i + 1} / {c.label} ↗</a>)}</div>}</section>}
      <section className="work-section" id="work"><div className="section-heading"><span className="eyebrow">{mode === 1 ? 'Inside the collection' : mode === 2 ? 'Follow a thread' : 'A few ways of seeing the world'}</span><span className="preview-tag">Proposed story structure / 03 chapters</span></div><div className="work-layout"><div className="chapter-list" aria-label="Explore a chapter">{chapters.map((c, i) => <button key={c.label} onClick={() => { setChapter(i); setLens('Overview'); }} aria-pressed={chapter === i}><span>0{i + 1}</span><span>{c.label}</span><span>{chapter === i ? '↗' : '+'}</span></button>)}</div><article className="chapter-detail" aria-live="polite"><div className="chapter-top"><span className="eyebrow">{selected.category}</span><div className="lens-controls" aria-label="Reading perspective">{['Overview', 'The question'].map(l => <button key={l} aria-pressed={lens === l} onClick={() => setLens(l)}>{l}</button>)}</div></div><h2>{lens === 'Overview' ? selected.title : selected.angle}</h2><p>{lens === 'Overview' ? selected.text : selected.question}</p><a className="text-link" href={selected.link} target="_blank" rel="noreferrer">{selected.cta} <span>↗</span></a><small className="content-note">Concept copy · {lens === 'The question' ? 'An authored prompt for a future case study, not AI output.' : 'A proposed chapter based on existing work; full case studies come next.'}</small></article></div></section>
      <section className="closing"><span className="eyebrow">The throughline</span><p>I love to design.<br/>I also love to <em>build.</em></p><a href="mailto:will+hello@dzierson.com">Let’s make something worth exploring. <span>↗</span></a></section>
    </main><footer><span>Will Dzierson © 2026</span><span>{direction.name} / Concept 0{mode + 1}</span><a href="https://www.linkedin.com/in/will-dzierson-1081963/" target="_blank" rel="noreferrer">LinkedIn ↗</a></footer>
  </div>;
}
