import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Folder, HardDrive, Search, ChevronRight, Globe2, Play, Pause, RotateCcw, Send, Sparkles, Mail, FileText, Film } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { folders, launch } from './model';
import { supabase } from '@/integrations/supabase/client';

export function Welcome() { return <div className="welcome-app"><span className="note-date">A NOTE FOR YOU</span><h1>Hi, I’m Will.<br/><em>Make yourself<br/>at home.</em></h1><p>I’m a designer and technologist. This is a little corner of the internet for the things I make, think about, and come back to.</p><button className="inline-action" onClick={() => launch('finder')}>Take a look around <ArrowUpRight size={15}/></button><span className="note-signature">Will</span></div>; }
export function Finder() {
  const [folder, setFolder] = useState<string | null>(null); const [search, setSearch] = useState('');
  const selected = folders.find(f => f.name === folder);
  return <div className="finder-app"><aside className="finder-sidebar"><small>FAVORITES</small><button className={!folder ? 'selected' : ''} onClick={() => setFolder(null)}><HardDrive size={16}/> Will’s drive</button>{folders.map(f => <button className={folder === f.name ? 'selected' : ''} key={f.name} onClick={() => setFolder(f.name)}><Folder size={15}/>{f.name}</button>)}</aside><div className="finder-main"><div className="finder-toolbar"><button aria-label="Back to drive" disabled={!folder} onClick={() => setFolder(null)}><ArrowLeft size={16}/></button><span>Will’s drive {folder && <> / {folder}</>}</span><label><Search size={13}/><input aria-label="Search folders" placeholder="Search" value={search} onChange={e => setSearch(e.target.value)}/></label></div>{!folder ? <div className="folder-grid">{folders.filter(f => f.name.toLowerCase().includes(search.toLowerCase())).map(f => <button key={f.name} onClick={() => setFolder(f.name)}><span className="folder-illustration"/><strong>{f.name}</strong><small>{f.caption}</small></button>)}{!folders.some(f => f.name.toLowerCase().includes(search.toLowerCase())) && <p>No folders match “{search}”.</p>}</div> : <div className="folder-open"><span className="folder-illustration"/><h2>{selected?.name}</h2><p>{selected?.caption}</p><button className="os-primary" onClick={() => selected && launch(selected.app)}>Open {selected?.name} <ArrowUpRight size={14}/></button><p className="muted">This folder opens its collection in a dedicated app.</p></div>}<div className="finder-status">{folder ? '1 collection' : '6 folders'}<span>Will’s drive</span></div></div></div>;
}
type Project = { id: string; title: string; client: string; description: string; project_images: { image_url: string; is_primary: boolean }[] };
export function Portfolio() {
  const [projects, setProjects] = useState<Project[]>([]); const [state, setState] = useState('loading'); const [selected, setSelected] = useState<Project | null>(null); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let alive = true; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 12000); setState('loading'); supabase.from('projects').select('id,title,client,description,project_images(image_url,is_primary)').eq('visible', true).order('sort_order', { ascending: true, nullsFirst: false }).limit(12).abortSignal(controller.signal).then(({ data, error }) => { if (alive) { setProjects((data as Project[]) || []); setState(error ? 'error' : 'ready'); } }); return () => { alive = false; clearTimeout(timer); controller.abort(); }; }, [attempt]);
  return <div className="browser-app"><div className="browser-chrome"><button aria-label="Back to projects" disabled={!selected} onClick={() => setSelected(null)}><ArrowLeft size={15}/></button><button aria-label="Reload projects" onClick={() => setAttempt(x => x + 1)}><RotateCcw size={13}/></button><div className="browser-address"><Globe2 size={12}/> dzierson.com / {selected ? `project / ${selected.title}` : 'projects'}</div><a href="https://dzierson.com/projects" target="_blank" rel="noreferrer" aria-label="Open live projects page"><ArrowUpRight size={15}/></a></div><div className="portfolio-page">{selected ? <article className="project-reading"><span className="os-eyebrow">{selected.client}</span><h2>{selected.title}</h2>{selected.project_images[0] && <img src={selected.project_images.find(i => i.is_primary)?.image_url || selected.project_images[0].image_url} alt={selected.title}/>}<ReactMarkdown>{selected.description}</ReactMarkdown><a className="inline-action" href={`https://dzierson.com/project/${selected.id}`} target="_blank" rel="noreferrer">Full case study ↗</a></article> : <><div className="portfolio-intro"><span className="os-eyebrow">SELECTED WORK</span><h2>Design meets<br/><em>possibility.</em></h2><p>Projects, products, and experiments by Will Dzierson.</p></div>{state === 'loading' && <p className="loading-app" role="status">Opening the project archive…</p>}{state === 'ready' && projects.length > 0 ? <div className="project-cards">{projects.map((p,i) => { const src = p.project_images.find(image => image.is_primary)?.image_url || p.project_images[0]?.image_url; return <button key={p.id} onClick={() => setSelected(p)}><div className={`project-art project-art-${i % 3}`}>{src ? <img src={src} alt="" loading="lazy" onError={e => { e.currentTarget.style.display = 'none'; }}/>: <Globe2 size={48} strokeWidth={.7}/>}</div><small>{p.client || 'Independent project'}</small><strong>{p.title}<ArrowUpRight size={15}/></strong></button>; })}</div> : state !== 'loading' && <><p className="archive-error">{state === 'error' ? 'The live archive is unavailable right now.' : 'No public projects were returned.'} <button onClick={() => setAttempt(x => x + 1)}>Try again</button></p><div className="project-cards"><a href="https://github.com/wdzierson/aspect-os" target="_blank" rel="noreferrer"><div className="project-art aspect-project"><div className="mini-os"><div/><div/><div/></div></div><small>Open-source / Interface systems</small><strong>AspectOS <ArrowUpRight size={15}/></strong></a><a href="https://os.dzierson.com" target="_blank" rel="noreferrer"><div className="project-art webos-project"><Globe2 size={70} strokeWidth={.6}/></div><small>Independent / AI-enabled webOS</small><strong>A place to experiment <ArrowUpRight size={15}/></strong></a></div></>}</>}<div className="portfolio-page-footer"><button onClick={() => launch('assistant')}>Ask about the work ↗</button></div></div></div>;
}
const notes = [
  { title: 'Designing & building', category: 'From the current portfolio', text: 'I am a designer and technologist, having always sat at the intersection of both. I love to design, and I also love to build.', footer: 'An excerpt from the existing portfolio introduction.' },
  { title: 'A more personal internet', category: 'Concept note · Draft', text: 'What if a portfolio felt like visiting someone’s studio? The finished work is there, but so are the records, the open notebooks, and the ideas that haven’t quite found their shape yet.', footer: 'Sample editorial copy for this concept, awaiting Will’s writing.' },
  { title: 'Leaving room for play', category: 'Concept note · Draft', text: 'A desktop makes room for small discoveries. A song in the background. A command that opens a door. A folder that invites a detour. The path through the work can be yours.', footer: 'Sample editorial copy for this concept, awaiting Will’s writing.' },
];
export function Notes() { const [index, setIndex] = useState(0); return <div className="notes-app"><aside><span className="os-eyebrow">FIELD NOTES</span>{notes.map((n,i) => <button key={n.title} className={i === index ? 'selected' : ''} onClick={() => setIndex(i)}><FileText size={14}/><span>{n.title}<small>{i ? 'Draft' : 'Introduction'}</small></span></button>)}</aside><article><span className="os-eyebrow">{notes[index].category}</span><h2>{notes[index].title}</h2><p>{notes[index].text}</p><small>{notes[index].footer}</small><span className="note-signature">W.</span></article></div>; }
const musicUrl = 'https://uilvozcryifnpldfpwiz.supabase.co/storage/v1/object/public/content_assets/music/Max_Richter__On_The_Nature_Of_Daylight%20copy.mp3';
const time = (value: number) => `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, '0')}`;
export function MusicPlayer() {
  const audio = useRef<HTMLAudioElement>(null); const [playing, setPlaying] = useState(false); const [position, setPosition] = useState(0); const [duration, setDuration] = useState(0); const [error, setError] = useState('');
  async function toggle() { if (!audio.current) return; if (playing) audio.current.pause(); else { setError(''); try { await audio.current.play(); } catch { setError('Couldn’t load the track. Try play again.'); } } }
  return <div className="music-app"><audio ref={audio} src={musicUrl} preload="none" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => setPlaying(false)} onTimeUpdate={e => setPosition(e.currentTarget.currentTime)} onLoadedMetadata={e => setDuration(Number.isFinite(e.currentTarget.duration) ? e.currentTarget.duration : 0)} onError={() => setError('The audio source is unavailable. Try again later.')}/><div className={`record-art ${playing ? 'playing' : ''}`}><span className="record-sleeve">THE BLUE<br/>NOTEBOOKS<small>MAX RICHTER</small></span><div className="vinyl"><span/></div><span className="stereo-label">33⅓ / STEREO</span></div><div className="track-info"><span>ON THE TURNTABLE</span><h2>On the Nature of Daylight</h2><p>Max Richter · The Blue Notebooks</p></div><div className="player-seek"><input aria-label="Seek in track" type="range" min="0" max={duration || 1} step=".1" value={position} disabled={!duration} onChange={e => { if (audio.current) audio.current.currentTime = Number(e.target.value); }}/><div><span>{time(position)}</span><span>{time(duration)}</span></div></div><div className="player-controls"><button aria-label="Restart track" onClick={() => { if (audio.current) audio.current.currentTime = 0; }}><RotateCcw size={15}/></button><button className="play-button" aria-label={playing ? 'Pause music' : 'Play music'} onClick={toggle}>{playing ? <Pause size={18}/> : <Play size={18}/>}</button><label>Vol<input aria-label="Volume" type="range" min="0" max="1" step=".05" defaultValue="1" onChange={e => { if (audio.current) audio.current.volume = Number(e.target.value); }}/></label></div>{error && <p className="media-error" role="alert">{error}</p>}</div>;
}
export function Videos() { return <div className="videos-app"><span className="os-eyebrow">THE SCREENING ROOM</span><h2>Worth a closer look.</h2><p>A home for favorite films, talks, and things to come back to.</p><video controls preload="none" src="https://uilvozcryifnpldfpwiz.supabase.co/storage/v1/object/public/project_images/z7q711ep35.mp4" aria-label="AspectOS demo"><a href="https://github.com/wdzierson/aspect-os">View the AspectOS demo on GitHub</a></video><div className="video-caption"><Film size={16}/><div><strong>AspectOS — a look inside</strong><small>Demo from the AspectOS repository</small></div></div><div className="video-placeholder">Your personal video shelf goes here.<small>Favorite videos haven’t been selected for this concept yet.</small></div></div>; }
export function Assistant() {
  const [input, setInput] = useState(''); const [messages, setMessages] = useState<{ role: string; text: string; links?: { label: string; href: string }[] }[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const mounted = useRef(true); const end = useRef<HTMLDivElement>(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => end.current?.scrollIntoView({ block: 'nearest' }), [messages, busy]);
  async function submit(text: string) { if (!text.trim() || busy) return; setMessages(m => [...m, { role: 'You', text }]); setInput(''); setBusy(true); setError(''); try { const { processUserMessage } = await import('@/services/chatService'); const result = await processUserMessage(text); if (mounted.current) setMessages(m => [...m, { role: 'Willbot', text: result.content, links: [...(result.projects || []).map(p => ({ label: p.title, href: `https://dzierson.com/project/${p.id}` })), ...(result.contentEntries || []).map(c => ({ label: c.title, href: `https://dzierson.com/content/${c.id}` }))] }]); } catch { if (mounted.current) { setInput(text); setError('Willbot couldn’t reach the portfolio service. Your question is ready to retry.'); } } finally { if (mounted.current) setBusy(false); } }
  return <div className="assistant-app"><div className="assistant-intro"><span className="assistant-symbol"><Sparkles size={24}/></span><div><h2>A guide to the work.</h2><p>Ask about Will’s projects, experience, or process.</p></div></div><div className="assistant-messages" aria-live="polite">{!messages.length && <><p className="assistant-disclosure">Willbot uses the portfolio’s existing RAG service. Questions are sent to that service when you submit. Answers can be imperfect; explore the linked work for context.</p><div className="assistant-suggestions">{['Show me recent work', 'Tell me about your AI experience', 'What’s been on your mind lately?'].map(s => <button key={s} onClick={() => submit(s)}>{s}<ChevronRight size={14}/></button>)}</div></>}{messages.map((m,i) => <div key={i} className={`assistant-message ${m.role === 'You' ? 'user' : ''}`}><small>{m.role}</small><ReactMarkdown>{m.text}</ReactMarkdown>{m.links?.map(l => <a key={l.href} href={l.href} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</div>)}{busy && <p role="status">Looking through the portfolio…</p>}{error && <p role="alert" className="media-error">{error}</p>}<div ref={end}/></div><form className="assistant-input" onSubmit={e => { e.preventDefault(); submit(input); }}><input aria-label="Question for Willbot" placeholder="Ask something about the work…" value={input} onChange={e => setInput(e.target.value)} maxLength={2000} disabled={busy}/><button aria-label="Send question" disabled={busy || !input.trim()}><Send size={17}/></button></form></div>;
}
export function Contact() { const [draft, setDraft] = useState(''); const [copied, setCopied] = useState(false); const [error, setError] = useState(''); async function copy() { try { await navigator.clipboard.writeText(draft); setCopied(true); } catch { setError('Copy wasn’t available. Select and copy the message below.'); } } return <div className="contact-app"><span className="contact-avatar">W.</span><h2>Let’s start a conversation.</h2><p>A question, an idea, or just a hello.</p><label htmlFor="contact-message">Your message</label><textarea id="contact-message" value={draft} onChange={e => { setDraft(e.target.value); setCopied(false); }} placeholder="Hi Will, I came across your work…"/><button className="os-primary" disabled={!draft.trim()} onClick={copy}>{copied ? 'Draft copied' : 'Copy message draft'} <Send size={14}/></button><p className="contact-connection">Telegram connection pending your handle.<br/>This preview does not send messages.</p>{error && <p role="alert">{error}</p>}<a className="inline-action" href={`mailto:will+hello@dzierson.com?body=${encodeURIComponent(draft)}`}><Mail size={14}/> Open in email instead ↗</a></div>; }
