const roles=[
 ['insidetracker','InsideTracker','VP, Product & Design','2026—','Leading product strategy and design for a preventative-health platform, translating biomarkers and scientific insight into useful guidance.'],
 ['kring','KRING','Head of Product & UX','2025–26','Product vision, UX strategy, and design across pre-seed ventures in health, sustainability, and energy.'],
 ['included-health','Included Health','Staff Design Technologist, AI','2024–25','Built and evaluated voice, real-time video, and multimodal AI prototypes. Coached product and design teams in AI-enabled workflows.'],
 ['noodle','Noodle AI','Co-founder','2023–25','Raised angel funding, assembled a team, and designed and co-built a personal medical-history product. The company has since dissolved.'],
 ['obvious','Obvious Ventures','Designer in Residence','2018–19','Advised founders on product strategy, research, design hiring, and team development. Led UX for DarwinAI’s explainability product.'],
 ['grand-rounds','Grand Rounds','Lead → Principal → Design Director','2014–18','Built and led the Product Design and Research function across physician tools, consumer health experiences, and internal care platforms.'],
 ['gigwalk','Gigwalk','Head of Design','2012–14','Directed product design, brand, research, and design systems for a distributed mobile-workforce platform.'],
 ['salesforce','Salesforce','Senior Experience Designer, Mobile','2011–12','Led a mobile application redesign and explored multimodal voice interaction with an advanced-concepts team.'],
 ['google','Google','Mobile User Interface Designer','2007–10','Designed early touch interfaces across Search, Local, Calendar, and other products. Led ethnographic research in Beijing and Chongqing.'],
 ['yahoo','Yahoo!','Interaction Designer, Mobile','2005–07','Designed the Mobile Portal and experiences spanning Messenger, Local, oneSearch, and Photos.'],
 ['earlier','Independent & studio work','Design, technology & interactive media','Earlier','Interactive work for Smithsonian, Lincoln Center, Dr. Seuss, IBM, Bose, Caterpillar, PepsiCo, John Hancock, Lockheed Martin, SoftBank Japan, and Harvard Medical School.'],
];
const brands=[['google','Google','Google'],['included-health','Included Health','Included Health'],['insidetracker','InsideTracker',''],['salesforce','Salesforce',''],['yahoo','Yahoo!',''],['smithsonian','Smithsonian','Smithsonian'],['optum','Optum','Optum'],['ibm','IBM',''],['bose','Bose',''],['caterpillar','Caterpillar',''],['obvious','Obvious Ventures',''],['lincoln-center','Lincoln Center',''],['lockheed-martin','Lockheed Martin',''],['dr-seuss','Dr. Seuss',''],['softbank','SoftBank','']];
export function BrandCollection({onSelect}:{onSelect:(brand:string,client:string)=>void}){return <section className="brand-collection"><div className="brand-intro"><span className="eyebrow">Selected teams & clients</span><span>Skills acquired working with world class companies, clients, and teams.</span></div><div className="brand-grid">{brands.map(([id,label,client])=><a key={id} href={client?`#client=${encodeURIComponent(client)}`:`#career=${id}`} onClick={e=>{e.preventDefault();onSelect(id,client);}} title={`Work with ${label}`}><img src={`/portfolio/logos/${id}.svg`} alt={label}/></a>)}</div></section>}
export default function Experience({selected}:{selected:string|null}){return <section className="career-page"><span className="eyebrow">Experience</span><h1>A builder’s perspective.<br/>At every scale.</h1><p>From early mobile products to AI-native ventures. A career moving between making the product and helping teams do their best work.</p><div className="career-roles">{roles.map(([id,name,role,dates,description])=><article className={selected===id||(selected&&['ibm','bose','caterpillar','lincoln-center','lockheed-martin','dr-seuss','softbank'].includes(selected)&&id==='earlier')?'is-selected':''} key={id}><span>{dates}</span><div><h2>{name}</h2><h3>{role}</h3><p>{description}</p></div></article>)}</div><p className="career-note">Alongside these roles: independent product design, engineering, and advisory work since 2019. Experience drawn from Will’s executive résumé.</p></section>}
