import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { SquareTerminal } from 'lucide-react';
import content from './content.json';
import { usePortfolioProjects, featuredIds, featuredCopy, cover } from './projects';
import ProjectGallery from './ProjectGallery';
import PortfolioChat from './PortfolioChat';
import { usePortfolioWriting } from './chat/sources';
import CareerReel from './CareerReel';
import HeroAtmosphere from './HeroAtmosphere';
import PracticeSignal from './motion/PracticeSignal';
import WorkImage from './motion/WorkImage';
import RiskDashboard from './dashboard/RiskDashboard';
import { publications, linkedin, lovableFeature } from './publications';
import Experience, { BrandCollection } from './Experience';
import { useSmoothScroll } from './useSmoothScroll';
const FloatingTerminal=lazy(()=>import('./FloatingTerminal'));
const mail=(subject:string)=>`mailto:will+folio@dzierson.com?subject=${encodeURIComponent(subject)}`;
export default function Practice(){
 const {projects,loading,error,retry}=usePortfolioProjects();
 const {articles,loading:writingLoading}=usePortfolioWriting();
 const scroll=useSmoothScroll();
 const [route,setRoute]=useState(()=>location.hash.slice(1)),[search,setSearch]=useState(''),[lens,setLens]=useState('Product leadership');
 const [terminalOpen,setTerminalOpen]=useState(false);const terminalTrigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const read=()=>setRoute(location.hash.slice(1));window.addEventListener('hashchange',read);window.addEventListener('popstate',read);return()=>{window.removeEventListener('hashchange',read);window.removeEventListener('popstate',read);};},[]);
 const params=new URLSearchParams(route);const current=projects.find(p=>p.id===params.get('case'));const essay=articles.find(e=>e.id===params.get('essay'))||content.essays.find(e=>e.id===params.get('essay'));const career=params.has('career');const archive=route==='projects'||params.has('client');const chat=route==='ask'||params.has('ask');const chatProject=projects.find(p=>p.id===params.get('ask'));const isCase=params.has('case');const isEssay=params.has('essay');
 function go(hash:string){history.pushState(null,'',hash?`#${hash}`:location.pathname);setRoute(hash);scroll(0,true);}
 function openCase(id:string){go(`case=${id}`);}
 function navigateSection(event:React.MouseEvent<HTMLAnchorElement>,id:string){event.preventDefault();go(id);requestAnimationFrame(()=>{const el=document.getElementById(id);if(el)scroll(el);});}
 const filter=params.get('client')||search;const filtered=projects.filter(p=>(params.has('client')?p.client:p.title+' '+p.client+' '+p.description+' '+p.tags.join(' ')).toLowerCase().includes(filter.toLowerCase()));
 const featured=featuredIds.map((id,i)=>({project:projects.find(p=>p.id===id),copy:featuredCopy[i],i})).filter(x=>x.project);
 const lead=projects.find(p=>p.id===featuredIds[0]);
 const home=!isCase&&!isEssay&&!archive&&!chat&&!career;
 return <div className={`practice ${home?'is-home':''}`}><a className="practice-skip" href="#main">Skip to content</a><header><a className="practice-name" href="/practice.html" onClick={e=>{e.preventDefault();go('');}}>Will Dzierson</a><nav aria-label="Main navigation"><a href="#projects" onClick={e=>{e.preventDefault();setSearch('');go('projects');}}>All work</a><a href="#practice" onClick={e=>navigateSection(e,'practice')}>About</a><a href="#inquiry" onClick={e=>navigateSection(e,'inquiry')}>Writing</a><a href="#ask" onClick={e=>{e.preventDefault();go('ask');}}>Ask AI</a><a className="contact-nav" href={mail('A conversation about your work')}>Contact ↗</a><button ref={terminalTrigger} className="terminal-trigger" aria-label="Open interactive terminal" aria-expanded={terminalOpen} onClick={()=>setTerminalOpen(v=>!v)}><SquareTerminal size={18} strokeWidth={1.5}/></button></nav></header><main id="main">
 {(loading||isEssay&&writingLoading)&&!home&&<p className="data-status" role="status">Loading the work…</p>}{error&&<p className="data-status" role="alert">The project collection couldn’t load. <button onClick={retry}>Try again</button></p>}
 {isCase&&current&&<article className="case-page"><button onClick={()=>go('projects')}>← All work</button><span className="eyebrow">{current.client} / {current.year}</span><h1>{current.title}</h1><div className="case-actions"><button className="text-link" onClick={()=>go(`ask=${current.id}`)}>Ask about this project ↗</button>{current.liveurl&&/^https?:\/\//.test(current.liveurl)&&<a className="text-link" href={current.liveurl} target="_blank" rel="noreferrer">Visit project ↗</a>}</div><ProjectGallery key={current.id} project={current}/><div className="case-prose"><aside><span className="eyebrow">My contribution</span><ReactMarkdown>{current.involvement||'Contribution details are being added.'}</ReactMarkdown></aside><section><h2>The work</h2><ReactMarkdown>{current.description}</ReactMarkdown></section></div><div className="case-next"><button onClick={()=>openCase(projects[(projects.indexOf(current)-1+projects.length)%projects.length].id)}>← Previous project</button><button onClick={()=>openCase(projects[(projects.indexOf(current)+1)%projects.length].id)}>Next project →</button></div></article>}
 {isCase&&!loading&&!error&&!current&&<section className="case-page"><h1>Project not found.</h1><button onClick={()=>go('projects')}>Browse all work →</button></section>}
 {essay&&<article className="essay-page"><button onClick={()=>go('inquiry')}>← Back to portfolio</button><span className="eyebrow">Essay / Working ideas</span><h1>{essay.title}</h1><ReactMarkdown>{essay.content}</ReactMarkdown></article>}
 {isEssay&&!writingLoading&&!essay&&<section className="essay-page"><h1>This essay isn’t available.</h1><a href="#inquiry">Browse the writing →</a></section>}
 {archive&&<section className="work-archive"><span className="eyebrow">The complete collection</span><h1>All work.</h1><p>Products, experiments, and research. Designed, built, and led across 25+ years.</p><div className="archive-tools"><label>Find a project<input aria-label="Find a project" type="search" placeholder="Search by project, client, or topic" value={filter} onChange={e=>{setSearch(e.target.value);if(params.has('client'))go('projects');}}/></label><span aria-live="polite">{filtered.length} / {projects.length} projects</span>{filter&&<button onClick={()=>{setSearch('');go('projects');}}>Clear filter ×</button>}</div><div className="archive-grid">{filtered.map(p=><a key={p.id} href={`#case=${p.id}`} onClick={e=>{e.preventDefault();openCase(p.id);}}><div className="archive-image">{cover(p)?<WorkImage treatment="archive" src={cover(p)!} alt={`${p.title} preview`} loading="lazy"/>:<span>Explore the case →</span>}</div><span>{p.client} / {p.year}</span><h2>{p.title}</h2><div className="archive-tags">{p.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}{p.tags.length>3&&<span>+{p.tags.length-3}</span>}</div></a>)}</div>{!loading&&!error&&!filtered.length&&<p>No matching projects. Try a different search.</p>}</section>}
 {career&&<Experience selected={params.get('career')}/>}
 {chat&&<PortfolioChat key={chatProject?.id||'all'} projects={projects} initialProject={chatProject} articles={articles} writingLoading={writingLoading}/>}
 {home&&<><section className="practice-hero"><HeroAtmosphere/><div><span className="eyebrow">Designer, technologist, founder</span><h1>From complex ideas<br/><span>to working products.</span></h1></div><div className="hero-context"><p>I conceive, design, build, and ship.{' '}<br/>25+ years connecting what’s possible{' '}<br/>with what people actually need.</p><div><span className="availability-dot"/><span>Currently: VP, Product & Design at <a href="https://www.insidetracker.com/" target="_blank" rel="noreferrer">InsideTracker</a></span></div></div></section>
 <CareerReel/>
 <BrandCollection onSelect={(id,client)=>go(client?`client=${encodeURIComponent(client)}`:`career=${id}`)}/>
 <section className="selected-work" id="work"><div className="section-top"><span className="eyebrow">01 / Selected work</span><span>From field research to production software.</span></div>
 {loading&&<div className="work-loading" role="status"><span>Loading selected work…</span></div>}
 {lead&&<article className="lead-case"><RiskDashboard projectId={lead.id}/><div className="lead-case-caption"><div><span>The Public Health Company / Decision intelligence</span><h2><a href={`#case=${lead.id}`} onClick={e=>{e.preventDefault();openCase(lead.id);}}>See the risk. Know where to act.</a></h2></div><div><strong>From disease signals to operational decisions.</strong><span>Founding designer · Research · TypeScript prototypes</span></div></div></article>}
 <div className="featured-grid">{featured.filter(x=>x.i>0).map(({project:p,copy,i})=><article className={`featured-project feature-${i}`} key={p!.id}><a className="featured-image" href={`#case=${p!.id}`} onClick={e=>{e.preventDefault();openCase(p!.id);}}><WorkImage src={cover(p!)!} alt={`${p!.title} preview`} width={i===1?2336:i===2?2624:i===3?1420:i===4?1212:3578} height={i===1?1752:i===2?1468:i===3?914:i===4?874:1868} loading="lazy"/></a><div><span className="eyebrow">{copy[2]}</span><h2><a href={`#case=${p!.id}`} onClick={e=>{e.preventDefault();openCase(p!.id);}}>{copy[0]}</a></h2><p>{copy[1]}</p></div></article>)}</div><a className="all-work-link" href="#projects" onClick={e=>{e.preventDefault();go('projects');}}>The complete collection <span>{projects.length||''} projects ↗</span></a></section>
 <PracticeSignal/>
 <section className="practice-section" id="practice"><div className="section-top"><span className="eyebrow">02 / The practice</span><h2>Close to the idea.<br/>Closer to the work.</h2></div><div className="practice-body"><p className="practice-statement">The most useful place to work is often between disciplines. I connect product strategy, research, design, and engineering—then stay with the work through implementation. Today, I lead Product & Design at InsideTracker. I still build.</p><div className="practice-tabs" aria-label="Explore my practice">{['Product leadership','Design & engineering','Founding'].map(l=><button aria-pressed={lens===l} onClick={()=>setLens(l)} key={l}>{l}</button>)}</div><div className="practice-perspective" aria-live="polite">{lens==='Product leadership'?<><h3>Lead through the work.</h3><p>At Grand Rounds, my work progressed from lead and principal design roles to Design Director, growing and coaching the Design & Research teams. My current VP role continues that player-coach approach.</p><span>Team development · Product direction · Cross-functional delivery</span></>:lens==='Design & engineering'?<><h3>Make the decisions testable.</h3><p>At Included Health, I built conversational prototypes and worked with clinical, product, and engineering partners. A comparative study of conventional, chat, and voice interfaces informed subsequent AI interaction patterns.</p><button className="text-link" onClick={()=>openCase('cc5b34e1-e0a7-4a59-b3b6-c9e814585c34')}>Explore the multimodal work ↗</button></>:<><h3>Own the problem and the product.</h3><p>At Noodle, I co-founded the company, helped raise angel funding, led design, and co-led engineering with contract engineers. The company dissolved; the experience remains part of how I evaluate product bets and execution.</p><button className="text-link" onClick={()=>openCase('e7149d46-fad6-477b-a91c-77e76723df7d')}>Explore Noodle ↗</button></>}</div><a className="text-link" href="#career=all" onClick={e=>{e.preventDefault();go('career=all');}}>The career behind the work ↗</a></div></section>
 <section className="inquiry-section" id="inquiry"><div className="section-top"><span className="eyebrow">03 / Writing & research</span><h2>Working ideas.</h2></div><div className="inquiry-layout"><div><p>I’m interested in how people understand, govern, and work with intelligent systems—and in bringing a builder’s perspective to teaching and research.</p><small className="inquiry-note">Published contributor, Mobile Persuasion — Stanford Persuasive Technology Lab.</small></div><div className="essay-list">{publications.map(p=><a key={p.url} href={p.url} target="_blank" rel="noreferrer"><span>{p.type}</span><h3>{p.title}</h3><span>↗</span></a>)}<div className="publishing-note"><span>Published on Medium</span><a href={lovableFeature} target="_blank" rel="noreferrer">Portfolio featured by Lovable ↗</a></div></div></div></section>
 <section className="contact-section"><span className="eyebrow">Good work starts with a conversation.</span><a href={mail('A conversation about your work')}>Let’s make something<br/>worth putting into the world. <span>↗</span></a><div><span>Saratoga Springs, New York</span><a href="mailto:will@dzierson.com">will@dzierson.com</a></div></section></>}
 </main>{terminalOpen&&<Suspense fallback={<div className="terminal-loading" role="status">Opening terminal…</div>}><FloatingTerminal onClose={()=>{setTerminalOpen(false);terminalTrigger.current?.focus({preventScroll:true});}} projects={projects} onCase={openCase}/></Suspense>}<footer><span>Will Dzierson © 2026</span><span>Conceive. Design. Build. Deploy.</span><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://medium.com/@willdzierson" target="_blank" rel="noreferrer">Medium ↗</a><a href="#projects" onClick={e=>{e.preventDefault();go('projects');}}>All work ↗</a></footer></div>;
}
